# Generated by Django 5.2.15 on 2026-06-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(db_index=True, max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title', 'author'],
                'indexes': [models.Index(fields=['title', 'author'], name='catalogue_b_title_1410d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(max_length=40, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalogue.book')),
            ],
            options={
                'verbose_name_plural': 'book copies',
                'ordering': ['book__title', 'inventory_code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('librarian', 'Librarian')], db_index=True, default='reader', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(db_index=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='catalogue.bookcopy')),
                ('loaned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'loaned_at'],
                'indexes': [models.Index(fields=['reader', 'returned_at'], name='catalogue_l_reader__fc6b5e_idx'), models.Index(fields=['copy', 'returned_at'], name='catalogue_l_copy_id_e40ccc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('copy',), name='one_active_loan_per_copy')],
            },
        ),
    ]
