# Generated by Codex on 2026-06-23

from django.db import migrations, models


def populate_reference_numbers(apps, schema_editor):
    Book = apps.get_model("catalogue", "Book")
    for book in Book.objects.filter(reference_number__isnull=True):
        book.reference_number = f"BOOK-{book.pk:04d}"
        book.save(update_fields=["reference_number"])


def clear_reference_numbers(apps, schema_editor):
    Book = apps.get_model("catalogue", "Book")
    Book.objects.update(reference_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="reference_number",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Reference number",
            ),
        ),
        migrations.RunPython(populate_reference_numbers, clear_reference_numbers),
        migrations.AlterField(
            model_name="book",
            name="reference_number",
            field=models.CharField(
                max_length=40,
                unique=True,
                verbose_name="Reference number",
            ),
        ),
        migrations.AlterField(
            model_name="bookcopy",
            name="inventory_code",
            field=models.CharField(
                max_length=40,
                unique=True,
                verbose_name="Book copy number",
            ),
        ),
        migrations.RemoveField(
            model_name="bookcopy",
            name="notes",
        ),
    ]
